"use client";
import * as React from "react";
import * as DialogPrimitive from "@radix-ui/react-dialog";
import {cn} from "../../lib/utils";
export const Dialog=DialogPrimitive.Root;
export const DialogTrigger=DialogPrimitive.Trigger;
export const DialogClose=DialogPrimitive.Close;
export const DialogTitle=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Title>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Title>>(({className,...props},ref)=><DialogPrimitive.Title ref={ref} className={cn("text-lg font-semibold text-white",className)} {...props}/>);DialogTitle.displayName="DialogTitle";
export const DialogDescription=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Description>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Description>>(({className,...props},ref)=><DialogPrimitive.Description ref={ref} className={cn("text-sm text-slate-300",className)} {...props}/>);DialogDescription.displayName="DialogDescription";
export const DialogContent=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Content>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>>(({className,children,...props},ref)=><DialogPrimitive.Portal><DialogPrimitive.Overlay className="fixed inset-0 z-40 bg-black/70"/><DialogPrimitive.Content ref={ref} className={cn("fixed left-1/2 top-1/2 z-50 max-h-[85vh] w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-xl border border-slate-600 bg-slate-900 p-6 text-white shadow-xl",className)} {...props}>{children}<DialogPrimitive.Close className="mt-5 rounded border border-slate-500 px-3 py-2 text-white">Close</DialogPrimitive.Close></DialogPrimitive.Content></DialogPrimitive.Portal>);DialogContent.displayName="DialogContent";
