"use client";
import {FormEvent,useEffect,useState} from "react";
type Approval={id:string;title:string;summary:string;risk:string;state:string};type Preview={id:string;intent:string;plan:Array<Record<string,unknown>>;read_only:boolean;confidence:number};
export default function ExecutiveDashboard({apiBase="/api/v1"}:{apiBase?:string}){
 const [snapshot,setSnapshot]=useState<any>(null),[approvals,setApprovals]=useState<Approval[]>([]),[command,setCommand]=useState(""),[preview,setPreview]=useState<Preview|null>(null),[live,setLive]=useState(false);
 async function refresh(){const [s,a]=await Promise.all([fetch(`${apiBase}/executive-dashboard/snapshot`).then(r=>r.json()),fetch(`${apiBase}/executive-dashboard/approvals`).then(r=>r.json())]);setSnapshot(s);setApprovals(a)}
 useEffect(()=>{refresh();const source=new EventSource(`${apiBase}/executive-dashboard/live`);source.onopen=()=>setLive(true);source.onerror=()=>setLive(false);source.onmessage=refresh;return()=>source.close()},[apiBase]);
 async function submit(e:FormEvent){e.preventDefault();setPreview(await fetch(`${apiBase}/executive-dashboard/commands/preview`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({utterance:command})}).then(r=>r.json()))}
 async function run(){if(!preview)return;await fetch(`${apiBase}/executive-dashboard/commands/${preview.id}/execute`,{method:"POST"});setPreview(null);setCommand("");refresh()}
 async function decide(id:string,approve:boolean){await fetch(`${apiBase}/executive-dashboard/approvals/${id}/decision`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({approve})});refresh()}
 return <main className="space-y-5 bg-slate-950 p-6 text-white"><header className="flex justify-between"><div><p className="text-xs text-cyan-400">MODULE 16</p><h1 className="text-2xl font-semibold">Executive Dashboard</h1></div><span className={live?"text-emerald-400":"text-amber-400"}>{live?"Live":"Reconnecting"}</span></header>
  <section className="grid gap-3 md:grid-cols-4">{Object.entries(snapshot?.data?.metrics||{}).map(([k,v])=><article key={k} className="rounded-xl bg-slate-900 p-4"><p className="text-xs text-slate-400">{k}</p><strong className="text-2xl">{String(v)}</strong></article>)}</section>
  <form onSubmit={submit} className="rounded-xl border border-slate-700 bg-slate-900 p-4"><label className="text-sm" htmlFor="atlas-command">Ask Atlas or prepare an action</label><div className="mt-2 flex gap-2"><input id="atlas-command" value={command} onChange={e=>setCommand(e.target.value)} className="flex-1 rounded bg-slate-800 p-3" placeholder="Show deadlines at risk this month"/><button className="rounded bg-cyan-500 px-4 text-slate-950">Preview</button></div>{preview&&<div className="mt-3 rounded bg-slate-800 p-3"><p>{preview.intent} · {Math.round(preview.confidence*100)}% confidence</p><p className="text-sm text-slate-300">{preview.read_only?"Read-only":"Requires approval before any action"}</p><button type="button" onClick={run} className="mt-2 rounded border border-cyan-400 px-3 py-1">{preview.read_only?"Run":"Send to approvals"}</button></div>}</form>
  <section><h2 className="text-lg font-semibold">Portfolio timeline</h2><div className="mt-2 space-y-2">{(snapshot?.data?.timeline||[]).map((item:any)=><article key={item.id} className="rounded-xl bg-slate-900 p-3"><div className="flex justify-between text-sm"><strong>{item.title}</strong><span className={item.at_risk?"text-red-300":"text-slate-400"}>{item.critical?"Critical path":""} {item.at_risk?"At risk":""}</span></div><div className="mt-2 h-2 rounded bg-slate-700"><div className="h-2 rounded bg-cyan-400" style={{width:`${Math.max(0,Math.min(100,(item.progress||0)*100))}%`}}/></div><p className="mt-1 text-xs text-slate-500">{new Date(item.start).toLocaleDateString()} - {new Date(item.end).toLocaleDateString()}</p></article>)}</div></section>
  <section><h2 className="text-lg font-semibold">Approval queue</h2><div className="mt-2 space-y-2">{approvals.map(a=><article key={a.id} className="rounded-xl bg-slate-900 p-4"><div className="flex justify-between"><strong>{a.title}</strong><span className="text-xs uppercase text-amber-300">{a.risk}</span></div><p className="mt-1 text-sm text-slate-300">{a.summary}</p><div className="mt-3 flex gap-2"><button onClick={()=>decide(a.id,true)} className="rounded bg-emerald-500 px-3 py-1 text-slate-950">Approve</button><button onClick={()=>decide(a.id,false)} className="rounded bg-slate-700 px-3 py-1">Reject</button></div></article>)}</div></section>
 </main>
}
