"use client";
import {useCallback,useEffect,useState} from "react";
import {authFetch} from "../lib/supabase";

type Integration={adapter_id:string;label:string;configured:boolean;live_accepted:boolean;write_accepted:boolean;last_successful_read:string|null;last_successful_write:string|null;scopes:string[];failure_reason:string|null;reconnect_action:string;write_probe_available:boolean;sandbox_resources:string[]};
export default function IntegrationReadiness({apiBase="/api/v1"}:{apiBase?:string}){
 const [items,setItems]=useState<Integration[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState("");
 const load=useCallback(async()=>{const r=await authFetch(`${apiBase}/integrations/acceptance`);if(!r.ok)throw Error("Could not load integration readiness");setItems((await r.json()).integrations)},[apiBase]);
 useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 async function readProbe(id:string){setBusy(id);setError("");try{const r=await authFetch(`${apiBase}/integrations/acceptance/${id}/probe/read`,{method:"POST"});if(!r.ok)throw Error((await r.json()).detail||"Read probe failed");await load()}catch(e){setError(e instanceof Error?e.message:"Read probe failed")}finally{setBusy("")}}
 async function writeProbe(item:Integration){const resource=item.sandbox_resources[0];if(!resource)return;const action="acceptance-test";if(!window.confirm(`Approve exactly: ${action} on ${resource}?`))return;setBusy(item.adapter_id);try{const r=await authFetch(`${apiBase}/integrations/acceptance/${item.adapter_id}/probe/write`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,resource,approval:{approved:true,adapter_id:item.adapter_id,action,resource},payload:{source:"integration-readiness"}})});if(!r.ok)throw Error((await r.json()).detail||"Write probe failed");await load()}catch(e){setError(e instanceof Error?e.message:"Write probe failed")}finally{setBusy("")}}
 return <section className="rounded-2xl border border-slate-700 bg-slate-950 p-5 text-white" aria-label="Integration readiness"><header><p className="text-xs text-cyan-400">CONFIGURATION</p><h2 className="text-xl font-semibold">Integration readiness</h2><p className="text-sm text-slate-400">Configured credentials are not accepted until a live read succeeds.</p></header>{error&&<p role="alert" className="mt-3 text-red-300">{error}</p>}<div className="mt-4 grid gap-3">{items.map(item=><article key={item.adapter_id} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">{item.label}</h3><p className="text-xs text-slate-400">{item.scopes.join(" · ")}</p></div><div className="flex gap-2 text-xs"><span className={item.configured?"text-amber-300":"text-slate-500"}>{item.configured?"Configured":"Not configured"}</span><span className={item.live_accepted?"text-emerald-300":"text-slate-500"}>{item.live_accepted?"Live accepted":"Untested"}</span></div></div>{item.failure_reason&&<p className="mt-2 text-sm text-red-300">{item.failure_reason}</p>}<p className="mt-2 text-xs text-slate-500">Read: {item.last_successful_read||"never"} · Write: {item.last_successful_write||"never"}</p><div className="mt-3 flex gap-2"><button disabled={!item.configured||busy===item.adapter_id} onClick={()=>readProbe(item.adapter_id)} className="rounded bg-cyan-500 px-3 py-1 text-sm text-slate-950 disabled:opacity-40">Test read</button>{item.write_probe_available&&<button disabled={!item.configured||!item.sandbox_resources.length||busy===item.adapter_id} onClick={()=>writeProbe(item)} className="rounded bg-amber-400 px-3 py-1 text-sm text-slate-950 disabled:opacity-40">Approve sandbox write</button>}<a href={item.reconnect_action} className="rounded border border-slate-600 px-3 py-1 text-sm">Reconnect</a></div></article>)}</div></section>
}
