"use client";
import {useState} from "react";
import {authFetch} from "../lib/supabase";
const sample={brand_or_segment:"luxury hospitality",sector:"luxury_hospitality",customer_job:"Give returning guests relevant personal service without covert tracking.",constraints:["consent","brand tone"],sources:[{source_id:"s1",url:"https://example.com/report",title:"Guest report",observed_at:"2026-09-22",finding:"Guests value recognition but want control over stored preferences."},{source_id:"s2",url:"https://example.com/ops",title:"Operations report",observed_at:"2026-09-22",finding:"Service recovery is delayed when context is split across teams."}],signals:[{signal_id:"privacy",statement:"Guests require visible preference controls.",source_ids:["s1"],importance:.9},{signal_id:"handoff",statement:"Staff handoffs lose actionable context.",source_ids:["s2"],importance:.8}],capabilities:[{capability_id:"consented-memory",description:"Tenant-scoped preference ledger with revocation",readiness:.8}]};
const sectors=["automotive","character_ip","hotel","luxury_hospitality","fashion","jewelry","other"];
type Studio={concepts:{concept_id:string;name:string;promise:string;evidence_refs:string[];scores:Record<string,number>}[];recommended_concept_id:string;validation_experiment:{method:string;success_metric:string;budget_limit:number};boundary:string};
type Evidence={sources:{source_id:string;url:string;title:string;observed_at:string;finding:string}[];signals:{signal_id:string;statement:string;source_ids:string[];importance:number}[];coverage_notes:string[];fetch_report:{source:string;status:string;items?:number;detail?:string}[];review_required:string};
async function post(path:string,body:object){const r=await authFetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw new Error(x.detail??JSON.stringify(x));return x}
export default function LuxuryVentureStudio(){
 const [brand,setBrand]=useState("Ferrari"),[sector,setSector]=useState("automotive"),[ticker,setTicker]=useState("RACE"),[notes,setNotes]=useState<string[]>([]),[report,setReport]=useState<Evidence["fetch_report"]>([]);
 const [brief,setBrief]=useState(JSON.stringify(sample,null,2)),[studio,setStudio]=useState<Studio|null>(null),[pitch,setPitch]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function fetchEvidence(){setBusy(true);setError("");try{const x:Evidence=await post("/api/v1/idea-incubator/luxury-venture-studio/evidence",{brand_or_segment:brand,sector,ticker:ticker.trim()||undefined});const b=JSON.parse(brief);b.brand_or_segment=brand;b.sector=sector;b.sources=x.sources;b.signals=x.signals.map(({signal_id,statement,source_ids,importance})=>({signal_id,statement,source_ids,importance}));setBrief(JSON.stringify(b,null,2));setNotes(x.coverage_notes);setReport(x.fetch_report);setStudio(null);setPitch("")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function generate(){setBusy(true);setError("");setPitch("");try{setStudio(await post("/api/v1/idea-incubator/luxury-venture-studio",JSON.parse(brief)))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function packagePitch(){if(!studio)return;setBusy(true);try{const x=await post("/api/v1/idea-incubator/luxury-venture-studio/pitch-package",{brief:JSON.parse(brief),concept_id:studio.recommended_concept_id});setPitch(x.markdown)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <section className="mb-6 rounded-xl border border-amber-700 bg-slate-900 p-5"><p className="text-xs text-amber-400">LUXURY VENTURE STUDIO (M19)</p><h2 className="text-xl font-semibold">Real free data to review-ready venture</h2><p className="mt-1 text-sm text-slate-400">SEC EDGAR XBRL facts, Stooq prices, Wikipedia/Wikidata, trade-press and Google News RSS - all free, no keys. Concepts, $0 validation, and pitch packaging. No affiliation, outreach, sale, or spend.</p>
 <div className="mt-4 grid gap-3 rounded border border-slate-700 bg-slate-950 p-3 md:grid-cols-[1fr_180px_120px_auto]"><label className="text-sm">Brand or segment<input aria-label="Brand or segment" value={brand} onChange={e=>setBrand(e.target.value)} className="mt-1 w-full rounded border border-slate-600 bg-slate-900 p-2"/></label><label className="text-sm">Sector<select aria-label="Sector" value={sector} onChange={e=>setSector(e.target.value)} className="mt-1 w-full rounded border border-slate-600 bg-slate-900 p-2">{sectors.map(s=><option key={s}>{s}</option>)}</select></label><label className="text-sm">Ticker (optional)<input aria-label="Ticker" value={ticker} onChange={e=>setTicker(e.target.value.toUpperCase())} placeholder="US-listed" className="mt-1 w-full rounded border border-slate-600 bg-slate-900 p-2"/></label><button onClick={fetchEvidence} disabled={busy} className="self-end rounded bg-amber-400 px-4 py-2 font-medium text-slate-950 disabled:opacity-40">{busy?"Working…":"Fetch real evidence"}</button></div>
 {report.length>0&&<div className="mt-2 flex flex-wrap gap-2 text-xs">{report.map(r=><span key={r.source} className={`rounded px-2 py-1 ${r.status==="ok"?"bg-emerald-950 text-emerald-300":r.status==="skipped"?"bg-slate-800 text-slate-400":"bg-red-950 text-red-300"}`}>{r.source}: {r.status}{typeof r.items==="number"?` (${r.items})`:""}</span>)}</div>}
 {notes.length>0&&<ul className="mt-2 list-inside list-disc text-xs text-slate-400">{notes.slice(0,3).map(n=><li key={n}>{n}</li>)}</ul>}
 <label className="mt-4 block text-sm">Grounded brief JSON<textarea aria-label="Grounded brief JSON" value={brief} onChange={e=>{setBrief(e.target.value);setStudio(null);setPitch("")}} rows={13} className="mt-1 w-full rounded border border-slate-600 bg-slate-950 p-3 font-mono text-xs"/></label><button onClick={generate} disabled={busy} className="mt-3 rounded bg-amber-400 px-4 py-2 font-medium text-slate-950 disabled:opacity-40">{busy?"Working…":"Generate scored concepts"}</button>{error&&<p role="alert" className="mt-3 rounded bg-red-950 p-3 text-red-200">{error}</p>}{studio&&<div className="mt-5 space-y-3"><div className="grid gap-3 lg:grid-cols-3">{studio.concepts.map(c=><article key={c.concept_id} className={`rounded border p-3 ${c.concept_id===studio.recommended_concept_id?"border-amber-400":"border-slate-700"}`}><strong>{c.name}</strong><p className="mt-1 text-sm text-slate-300">{c.promise}</p><dl className="mt-2 text-xs text-slate-400">{Object.entries(c.scores).map(([k,v])=><div key={k} className="flex justify-between"><dt>{k.replaceAll("_"," ")}</dt><dd>{v}</dd></div>)}</dl><p className="mt-2 text-xs">Evidence: {c.evidence_refs.join(", ")}</p></article>)}</div><div className="rounded bg-slate-950 p-3 text-sm"><b>$0 next proof:</b> {studio.validation_experiment.method}<br/><span className="text-slate-400">Success: {studio.validation_experiment.success_metric}</span></div><button onClick={packagePitch} disabled={busy} className="rounded border border-amber-400 px-3 py-2 text-sm">Build review-only pitch</button><p className="text-xs text-slate-500">{studio.boundary}</p></div>}{pitch&&<pre className="mt-4 max-h-96 overflow-auto whitespace-pre-wrap rounded bg-black/40 p-3 text-xs">{pitch}</pre>}</section>
}
