"use client";
import {useState} from "react";
import {authFetch} from "../lib/supabase";
const sample={brand_or_segment:"luxury hospitality",sector:"luxury_hospitality",customer_job:"Give returning guests relevant personal service without covert tracking.",constraints:["consent","brand tone"],sources:[{source_id:"s1",url:"https://example.com/report",title:"Guest report",observed_at:"2026-09-22",finding:"Guests value recognition but want control over stored preferences."},{source_id:"s2",url:"https://example.com/ops",title:"Operations report",observed_at:"2026-09-22",finding:"Service recovery is delayed when context is split across teams."}],signals:[{signal_id:"privacy",statement:"Guests require visible preference controls.",source_ids:["s1"],importance:.9},{signal_id:"handoff",statement:"Staff handoffs lose actionable context.",source_ids:["s2"],importance:.8}],capabilities:[{capability_id:"consented-memory",description:"Tenant-scoped preference ledger with revocation",readiness:.8}]};
type Studio={concepts:{concept_id:string;name:string;promise:string;evidence_refs:string[];scores:Record<string,number>}[];recommended_concept_id:string;validation_experiment:{method:string;success_metric:string;budget_limit:number};boundary:string};
async function post(path:string,body:object){const r=await authFetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw new Error(x.detail??JSON.stringify(x));return x}
export default function LuxuryVentureStudio(){
 const [brief,setBrief]=useState(JSON.stringify(sample,null,2)),[studio,setStudio]=useState<Studio|null>(null),[pitch,setPitch]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function generate(){setBusy(true);setError("");setPitch("");try{setStudio(await post("/api/v1/idea-incubator/luxury-venture-studio",JSON.parse(brief)))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function packagePitch(){if(!studio)return;setBusy(true);try{const x=await post("/api/v1/idea-incubator/luxury-venture-studio/pitch-package",{brief:JSON.parse(brief),concept_id:studio.recommended_concept_id});setPitch(x.markdown)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <section className="mb-6 rounded-xl border border-amber-700 bg-slate-900 p-5"><p className="text-xs text-amber-400">LUXURY VENTURE STUDIO</p><h2 className="text-xl font-semibold">Evidence to review-ready venture</h2><p className="mt-1 text-sm text-slate-400">Concepts, $0 validation, and pitch packaging. No affiliation, outreach, sale, or spend.</p><label className="mt-4 block text-sm">Grounded brief JSON<textarea aria-label="Grounded brief JSON" value={brief} onChange={e=>{setBrief(e.target.value);setStudio(null);setPitch("")}} rows={13} className="mt-1 w-full rounded border border-slate-600 bg-slate-950 p-3 font-mono text-xs"/></label><button onClick={generate} disabled={busy} className="mt-3 rounded bg-amber-400 px-4 py-2 font-medium text-slate-950 disabled:opacity-40">{busy?"Working…":"Generate scored concepts"}</button>{error&&<p role="alert" className="mt-3 rounded bg-red-950 p-3 text-red-200">{error}</p>}{studio&&<div className="mt-5 space-y-3"><div className="grid gap-3 lg:grid-cols-3">{studio.concepts.map(c=><article key={c.concept_id} className={`rounded border p-3 ${c.concept_id===studio.recommended_concept_id?"border-amber-400":"border-slate-700"}`}><strong>{c.name}</strong><p className="mt-1 text-sm text-slate-300">{c.promise}</p><dl className="mt-2 text-xs text-slate-400">{Object.entries(c.scores).map(([k,v])=><div key={k} className="flex justify-between"><dt>{k.replaceAll("_"," ")}</dt><dd>{v}</dd></div>)}</dl><p className="mt-2 text-xs">Evidence: {c.evidence_refs.join(", ")}</p></article>)}</div><div className="rounded bg-slate-950 p-3 text-sm"><b>$0 next proof:</b> {studio.validation_experiment.method}<br/><span className="text-slate-400">Success: {studio.validation_experiment.success_metric}</span></div><button onClick={packagePitch} disabled={busy} className="rounded border border-amber-400 px-3 py-2 text-sm">Build review-only pitch</button><p className="text-xs text-slate-500">{studio.boundary}</p></div>}{pitch&&<pre className="mt-4 max-h-96 overflow-auto whitespace-pre-wrap rounded bg-black/40 p-3 text-xs">{pitch}</pre>}</section>
}
