"use client";
import {useMemo,useState} from "react";
import {authFetch} from "../lib/supabase";
import GuidedJourneys from "./GuidedJourneys";
import LuxuryVentureStudio from "./LuxuryVentureStudio";
type Action={label:string;method:"GET"|"POST";path:string;sample?:object;effect?:boolean};
type Product={id:number;name:string;promise:string;actions:Action[]};
const products:Product[]=[
 {id:18,name:"Experiment Runner",promise:"Collect public signals, prepare a bounded experiment, and record measured outcomes.",actions:[{label:"Create durable run",method:"POST",path:"/api/v1/side-hustle-scraper/durable-runs",sample:{title:"Research tutoring pilot",first_experiment:"Measure five qualified signups",max_budget:0,source_urls:[]}},{label:"List durable runs",method:"GET",path:"/api/v1/side-hustle-scraper/durable-runs"}]},
 {id:19,name:"Idea Incubator",promise:"Rank the cheapest tests that reduce uncertainty before spending.",actions:[{label:"Rank assumption tests",method:"POST",path:"/api/v1/idea-incubator/assumption-burn-down",sample:{assumptions:[{id:"demand",statement:"Researchers will pay",probability_true:.5}],tests:[{id:"interviews",assumption_id:"demand",positive_result_probability:.5,posterior_if_positive:.9,posterior_if_negative:.1,cost:0,hours:2,method:"Five interviews",success_metric:"Three commitments"}],budget:0}}]},
 {id:20,name:"Cognitive Worker",promise:"Keep plans, simulations, real execution, and independent verification separate.",actions:[{label:"Build execution-truth ledger",method:"POST",path:"/api/v1/api/modules/20/execution-truth-ledger",sample:{items:[{id:"plan-1",claim:"Workflow prepared",state:"planned",evidence_ids:[]}]}}]},
 {id:21,name:"Claire",promise:"Pair an owner-controlled computer and verify tamper-evident result receipts.",actions:[{label:"Create pairing challenge",method:"POST",path:"/api/v1/claire/devices/pairing-challenge",sample:{}} ,{label:"List paired devices",method:"GET",path:"/api/v1/claire/devices"}]},
 {id:22,name:"Tools Hub",promise:"Discover, review, approve, install, and roll back tools with evidence.",actions:[{label:"Discover tools",method:"POST",path:"/api/v1/tools-hub/discoveries",sample:{query:"reproducible science data tools"}},{label:"View portfolio",method:"GET",path:"/api/v1/tools-hub/portfolio"}]},
 {id:23,name:"Study Abroad",promise:"Trace application requirements and essay claims to owner and official evidence.",actions:[{label:"Build evidence matrix",method:"POST",path:"/api/v1/study-abroad/application-evidence-matrix",sample:{requirements:[],claims:[],owner_records:[],official_sources:[]}}]},
 {id:24,name:"Billing",promise:"Preview exact commitments and keep every charge behind approval.",actions:[{label:"List plans",method:"GET",path:"/api/v1/billing/plans"},{label:"Preview commitment",method:"POST",path:"/api/v1/billing/commitment-preview",sample:{plan_id:"pro",currency:"USD",quantity:1,tax_rate_percent:0,renewal_interval:"month",cancellation_policy:"Cancel before renewal"}}]},
 {id:25,name:"Knowledge Copilot",promise:"Capture cited knowledge and persist tenant-scoped provenance events.",actions:[{label:"List provenance events",method:"GET",path:"/api/v1/knowledge-copilot/artifact-events"},{label:"Start capture session",method:"POST",path:"/api/v1/knowledge-copilot/sessions",sample:{device_id:"paired-device",selected_screen_ids:["screen-1"],redactions:[]},effect:true}]}
];
export default function ModuleWorkbench(){
 const [productId,setProductId]=useState(18),[actionIndex,setActionIndex]=useState(0),[body,setBody]=useState(""),[result,setResult]=useState(""),[busy,setBusy]=useState(false),[reviewed,setReviewed]=useState(false);
 const product=useMemo(()=>products.find(x=>x.id===productId)!,[productId]);const action=product.actions[actionIndex]??product.actions[0];
 function selectProduct(id:number){setProductId(id);setActionIndex(0);const p=products.find(x=>x.id===id)!;setBody(JSON.stringify(p.actions[0].sample??{},null,2));setResult("");setReviewed(false)}
 function selectAction(index:number){setActionIndex(index);setBody(JSON.stringify(product.actions[index].sample??{},null,2));setResult("");setReviewed(false)}
 async function run(){setBusy(true);setResult("");try{let parsed:unknown=undefined;if(action.method==="POST")parsed=JSON.parse(body||"{}");const response=await authFetch(action.path,{method:action.method,headers:{"Content-Type":"application/json"},body:action.method==="POST"?JSON.stringify(parsed):undefined});const text=await response.text();let shown=text;try{shown=JSON.stringify(JSON.parse(text),null,2)}catch{}setResult(`${response.status} ${response.statusText}\n${shown}`)}catch(error){setResult(`Request blocked: ${error instanceof Error?error.message:String(error)}`)}finally{setBusy(false)}}
 return <><GuidedJourneys/><LuxuryVentureStudio/><div className="grid gap-5 lg:grid-cols-[280px_1fr]"><aside className="space-y-2">{products.map(p=><button key={p.id} onClick={()=>selectProduct(p.id)} className={`w-full rounded-xl border p-3 text-left ${p.id===productId?"border-cyan-400 bg-cyan-950/40":"border-slate-700 bg-slate-900"}`}><span className="text-xs text-cyan-400">M{p.id}</span><strong className="block">{p.name}</strong></button>)}</aside><article className="rounded-xl border border-slate-700 bg-slate-900 p-5"><span className="text-xs text-cyan-400">M{product.id} PRODUCT WORKBENCH</span><h2 className="mt-1 text-2xl font-semibold">{product.name}</h2><p className="mt-2 text-slate-300">{product.promise}</p><label className="mt-5 block text-sm">Action<select value={actionIndex} onChange={e=>selectAction(Number(e.target.value))} className="mt-1 w-full rounded border border-slate-600 bg-slate-950 p-2">{product.actions.map((x,i)=><option value={i} key={x.label}>{x.method} - {x.label}</option>)}</select></label><div className="mt-3 rounded bg-slate-950 p-3 font-mono text-xs text-cyan-200">{action.method} {action.path}</div>{action.method==="POST"&&<label className="mt-3 block text-sm">Request JSON<textarea value={body} onChange={e=>{setBody(e.target.value);setReviewed(false)}} rows={12} spellCheck={false} className="mt-1 w-full rounded border border-slate-600 bg-slate-950 p-3 font-mono text-xs"/></label>}{action.effect&&<label className="mt-3 flex gap-2 rounded border border-amber-600/60 bg-amber-950/30 p-3 text-sm"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed this exact action and understand it starts a device capture session.</label>}<button disabled={busy||(action.effect&&!reviewed)} onClick={run} className="mt-4 rounded bg-cyan-400 px-4 py-2 font-medium text-slate-950 disabled:cursor-not-allowed disabled:opacity-40">{busy?"Running…":"Run exact action"}</button><pre aria-live="polite" className="mt-4 min-h-32 overflow-auto whitespace-pre-wrap rounded bg-black/40 p-3 text-xs text-slate-200">{result||"Response and failure details appear here."}</pre></article></div></>
}
