"""Evidence-led political and social analysis for audit rows 1760-1809.

All methods preserve provenance, competing explanations, affected-group voice and
uncertainty. Outputs are analysis, never political targeting, propaganda, coercion,
surveillance, diplomatic commitments, security operations, or eligibility decisions.
"""
from __future__ import annotations
from statistics import mean
from typing import Any
ROWS=dict(enumerate('''Revolution|Democratization|Authoritarianism|Nationalism|Ethnicity|Race Relations|Gender Relations|Class Analysis|Stratification|Mobility|Inequality|Poverty|Social Exclusion|Social Capital|Social Cohesion|Social Trust|Civic Engagement|Political Participation|Public Opinion|Political Communication|Media Effects|Propaganda|Framing|Agenda Setting|Priming|Persuasion|Attitude Change|Cognitive Dissonance|Social Influence|Conformity|Obedience|Compliance|Group Dynamics|Groupthink|Polarization|Conflict Resolution|Negotiation|Mediation|Diplomacy|International Relations|Foreign Policy|Security Studies|Terrorism|Counterterrorism|Peace Studies|Human Rights|Humanitarian Action|Development Studies|Globalization|Global Governance'''.split('|'),1760))
PROFILES={
1760:('process_tracing',['events','actors','institutions'],['grievances','mobilization','state_response','critical_junctures']),1761:('transition_analysis',['events','institutions','elections'],['contestability','participation','rights','civilian_control']),1762:('authoritarian_resilience',['institutions','coercion','legitimation'],['repression','cooptation','information_control','elite_cohesion']),
1763:('nationalism_analysis',['claims','symbols','institutions'],['civic','ethnic','anti_colonial','state_building']),1764:('ethnicity_analysis',['groups','contexts','institutions'],['self_identification','boundary_making','power','intersectionality']),1765:('race_relations',['groups','outcomes','institutions'],['disparity','discrimination_evidence','segregation','repair']),1766:('gender_relations',['groups','outcomes','institutions'],['roles','power','care','intersectionality']),1767:('class_analysis',['groups','resources','institutions'],['ownership','occupation','income','power']),1768:('stratification',['strata','outcomes','dimensions'],['rank','closure','inheritance','intersectionality']),1769:('mobility_analysis',['origin_destination_matrix'],['absolute_mobility','upward','downward','persistence']),1770:('inequality_analysis',['values'],['gini','distribution','top_share','between_group_limits']),1771:('poverty_analysis',['households','poverty_line'],['headcount','gap','severity','multidimensional_deprivation']),1772:('exclusion_analysis',['groups','dimensions'],['economic','social','political','service_access']),1773:('social_capital',['networks','ties'],['bonding','bridging','linking','resource_access']),1774:('cohesion_analysis',['groups','indicators'],['belonging','solidarity','conflict','institutional_inclusion']),1775:('trust_analysis',['responses','institutions'],['interpersonal','institutional','generalized','uncertainty']),1776:('civic_engagement',['activities','population'],['volunteering','associations','deliberation','collective_action']),1777:('participation_analysis',['activities','population'],['voting','protest','contact','barriers']),
1778:('opinion_estimation',['responses'],['weighted_estimate','sampling','nonresponse','question_wording']),1779:('communication_analysis',['messages','audiences','channels'],['sender','message','channel','reception']),1780:('media_effects',['exposed','comparison'],['difference_in_means','selection_bias','spillover','causal_limits']),1781:('propaganda_detection',['messages'],['source_concealment','manipulative_devices','false_dilemma','dehumanization']),1782:('frame_analysis',['texts','frames'],['problem_definition','causal_interpretation','moral_evaluation','treatment']),1783:('agenda_setting',['media_salience','public_salience'],['salience_association','lag','confounders','causal_limits']),1784:('priming_analysis',['exposure','evaluation_criteria'],['criterion_shift','pre_post','alternative_explanations','causal_limits']),1785:('persuasion_analysis',['pre','post'],['change','attrition','durability','autonomy']),1786:('attitude_change',['waves'],['direction','magnitude','stability','measurement_invariance']),1787:('dissonance_analysis',['beliefs','behavior'],['inconsistency','rationalization','belief_change','behavior_change']),1788:('influence_analysis',['network','actions'],['centrality','diffusion','homophily','peer_effect_limits']),1789:('conformity_analysis',['individual_choices','group_norm'],['alignment','private_acceptance_unknown','unanimity','independence']),1790:('obedience_analysis',['instructions','responses','authority_context'],['authority','escalation','dissent','right_to_refuse']),1791:('compliance_analysis',['requests','responses'],['request_strategy','consent','refusal','power_asymmetry']),
1792:('group_dynamics',['members','interactions'],['roles','norms','status','communication']),1793:('groupthink_risk',['decision_process'],['dissent','alternatives','independent_review','leader_impartiality']),1794:('polarization',['group_positions'],['between_group_distance','within_group_spread','sorting','affective_limits']),1795:('conflict_resolution',['parties','issues','interests'],['positions','interests','needs','options']),1796:('negotiation',['parties','offers','reservation_points'],['zopa','tradeoffs','batna','agreement_requires_approval']),1797:('mediation',['parties','issues','interests'],['neutrality','confidentiality','agenda','party_owned_outcome']),1798:('diplomacy',['actors','issues','constraints'],['interests','signals','channels','commitment_risk']),
1799:('international_relations',['actors','interactions','system'],['power','institutions','interdependence','ideas']),1800:('foreign_policy',['objectives','options','constraints'],['interests','instruments','tradeoffs','second_order_effects']),1801:('security_studies',['assets','threats','vulnerabilities'],['likelihood','impact','resilience','human_security']),1802:('terrorism_research',['incidents','definitions'],['targets','tactics','claimed_motives','definition_limits']),1803:('counterterrorism_review',['measures','objectives','rights_constraints'],['effectiveness','displacement','rights','oversight']),1804:('peace_studies',['conflict','actors','drivers'],['negative_peace','positive_peace','structural_violence','reconciliation']),1805:('human_rights',['facts','rights_framework'],['right','duty_bearer','alleged_interference','remedy']),1806:('humanitarian_action',['needs','population','constraints'],['humanity','neutrality','impartiality','independence']),1807:('development_studies',['indicators','population','interventions'],['capabilities','distribution','sustainability','local_ownership']),1808:('globalization',['flows','places','periods'],['trade','finance','migration','information']),1809:('global_governance',['institutions','issue','stakeholders'],['mandate','representation','accountability','coordination'])}
class AnalysisError(ValueError):pass
def _need(d,keys):
 m=[k for k in keys if d.get(k) in (None,[],{})]
 if m:raise AnalysisError('missing required inputs: '+', '.join(m))
def _gini(v):
 v=sorted(float(x) for x in v)
 if any(x<0 for x in v) or not v or sum(v)==0:raise AnalysisError('values must be non-negative with positive sum')
 n=len(v);return sum((2*i-n-1)*x for i,x in enumerate(v,1))/(n*sum(v))
def _special(i,d):
 if i==1769:
  m=d['origin_destination_matrix'];total=sum(map(sum,m));up=sum(m[a][b] for a in range(len(m)) for b in range(len(m[a])) if b>a);down=sum(m[a][b] for a in range(len(m)) for b in range(len(m[a])) if b<a);return {'absolute_mobility':round((up+down)/total,4),'upward':round(up/total,4),'downward':round(down/total,4),'persistence':round(1-(up+down)/total,4)}
 if i==1770:
  v=d['values'];return {'gini':round(_gini(v),4),'mean':mean(v),'count':len(v),'normative_threshold_applied':False}
 if i==1771:
  h=d['households'];line=float(d['poverty_line']);g=[max(0,line-float(x['resource']))/line for x in h];return {'headcount_ratio':round(sum(x>0 for x in g)/len(g),4),'poverty_gap':round(mean(g),4),'severity':round(mean(x*x for x in g),4)}
 if i==1778:
  rs=d['responses'];den=sum(float(x.get('weight',1)) for x in rs);return {'weighted_estimate':round(sum(float(x['value'])*float(x.get('weight',1)) for x in rs)/den,4),'n':len(rs),'margin_of_error_claimed':False}
 if i==1780:return {'exposed_mean':mean(d['exposed']),'comparison_mean':mean(d['comparison']),'difference_in_means':round(mean(d['exposed'])-mean(d['comparison']),4),'causal_effect_claimed':False}
 if i==1783:
  a=d['media_salience'];b=d['public_salience'];
  if len(a)!=len(b) or len(a)<2:raise AnalysisError('salience series must align')
  ma,mb=mean(a),mean(b);num=sum((x-ma)*(y-mb) for x,y in zip(a,b));den=(sum((x-ma)**2 for x in a)*sum((y-mb)**2 for y in b))**.5;return {'salience_correlation':None if den==0 else round(num/den,4),'causal_effect_claimed':False}
 if i in (1785,1786):
  before=d['pre'] if i==1785 else d['waves'][0];after=d['post'] if i==1785 else d['waves'][-1];return {'mean_change':round(mean(after)-mean(before),4),'wave_count':2 if i==1785 else len(d['waves']),'individual_causation_claimed':False}
 if i==1794:
  gp=d['group_positions'];means={k:mean(v) for k,v in gp.items()};return {'group_means':means,'between_group_distance':round(max(means.values())-min(means.values()),4),'polarized_person_labeling':False}
 if i==1796:
  r=d['reservation_points'];buyer=float(r['buyer_max']);seller=float(r['seller_min']);return {'zopa_exists':buyer>=seller,'zopa':[seller,buyer] if buyer>=seller else None,'agreement_made':False,'offers':d['offers']}
 return None
def analyze(row_id:int,payload:dict[str,Any])->dict[str,Any]:
 if row_id not in ROWS:raise AnalysisError('unsupported row')
 method,required,lenses=PROFILES[row_id];_need(payload,required);sources=payload.get('sources',[])
 if not sources or any(not x.get('source_id') or not x.get('observed_at') for x in sources):raise AnalysisError('sources require source_id and observed_at')
 special=_special(row_id,payload)
 findings=special or {'evidence_map':{lens:[x['source_id'] for x in sources if lens in x.get('supports',[])] for lens in lenses},'lens_status':{lens:'evidence_supplied' if any(lens in x.get('supports',[]) for x in sources) else 'evidence_gap' for lens in lenses}}
 return {'row_id':row_id,'capability':ROWS[row_id],'method':method,'findings':findings,'lenses':lenses,'competing_explanations':payload.get('competing_explanations',[]),'affected_group_inputs':payload.get('affected_group_inputs',[]),'limitations':payload.get('limitations',[]),'sources':sources,'status':'analysis_for_qualified_human_review','actions_taken':[],'boundary':'Analysis only. Do not target political beliefs or protected groups, manipulate, propagandize, coerce, surveil, operationalize violence, make diplomatic commitments, allocate aid, or determine rights. Preserve lawful dissent, consent, privacy, human rights, local voice and accountable human decisions.'}
