"""Import every SQLAlchemy model so Alembic sees the complete production schema."""
import app.core.collection as _model_0  # noqa: F401
import app.core.discovery as _model_1  # noqa: F401
import app.core.outcomes as _model_2  # noqa: F401
import app.core.vector_store as _model_3  # noqa: F401
import app.market.models as _model_4  # noqa: F401
import app.modules.m00_approval_center.service as _model_5  # noqa: F401
import app.modules.m01_opportunity_discovery.service as _model_6  # noqa: F401
import app.modules.m02_competition_manager.onboarding as _model_7  # noqa: F401
import app.modules.m02_competition_manager.profile_corpus as _model_8  # noqa: F401
import app.modules.m02_competition_manager.sql_repository as _model_9  # noqa: F401
import app.modules.m03_grant_writer.corpus as _model_10  # noqa: F401
import app.modules.m04_research_scientist.surveillance as _model_11  # noqa: F401
import app.modules.m05_outreach_manager.sql_repository as _model_12  # noqa: F401
import app.modules.m06_social_media_manager.sql_repository as _model_13  # noqa: F401
import app.modules.m07_brand_collaboration.sql_repository as _model_14  # noqa: F401
import app.modules.m08_startup_growth.sql_repository as _model_15  # noqa: F401
import app.modules.m09_knowledge_workspace.repository as _model_16  # noqa: F401
import app.modules.m10_email_assistant.sql_repository as _model_17  # noqa: F401
import app.modules.m11_calendar_intelligence.sql_repository as _model_18  # noqa: F401
import app.modules.m13_browser_agent.application_store as _model_19  # noqa: F401
import app.modules.m13_browser_agent.store as _model_20  # noqa: F401
import app.modules.m14_project_builder.sql_repository as _model_21  # noqa: F401
import app.modules.m15_document_generator.sql_repository as _model_22  # noqa: F401
import app.modules.m16_executive_dashboard.repository as _model_23  # noqa: F401
import app.modules.m19_idea_incubator.repository as _model_24  # noqa: F401
import app.modules.m20_general_cognitive_worker.sql_repository as _model_25  # noqa: F401
import app.modules.m21_claire.durable_execution as _model_26  # noqa: F401
import app.modules.m21_claire.personalization as _model_27  # noqa: F401
import app.modules.m23_study_abroad.advising as _model_28  # noqa: F401
import app.modules.m23_study_abroad.interview as _model_29  # noqa: F401
import app.modules.m23_study_abroad.story as _model_30  # noqa: F401
import app.modules.m24_billing.repository as _model_31  # noqa: F401
